@startuml
!include Style.puml
skinparam ArrowFontStyle plain

skinparam participant {
    BackgroundColor #F5F0FF
    BorderColor black
    FontColor black
}

actor User

participant ":ui" as ui
participant ":parser" as parser
participant "<<class>>\nMeal" as Meal

User-> ui : input: infoMeal chicken rice
activate ui

ui -> parser : parseCommand("infoMeal chicken rice")
activate parser

parser -> Meal : handleInfoMeal("infoMeal chicken rice")
activate Meal
Meal --> parser : parseInfoMeal("infoMeal chicken rice")
parser -> Meal : return name
deactivate parser

Meal -> Meal : print the nutrient details of the meal based on its name
Meal --> ui
deactivate Meal

ui --> User

@enduml