@startuml
'https://plantuml.com/sequence-diagram

participant ":Ui" as Ui
participant ":StorageManager" as StorageManager

participant "xyzNutrientStorage:Storage" as xyzNutrientStorage
participant "xyzStorage:Storage" as xyzStorage

hide footbox
!pragma teoz true

Ui -> StorageManager**: StorageManager(...)
activate StorageManager

alt successful case
StorageManager -> StorageManager: loadXYZNutrient(xyzNutrientStorage)
activate StorageManager
StorageManager -> xyzNutrientStorage: readFile()
activate xyzNutrientStorage
xyzNutrientStorage --> StorageManager: read pre-defined nutritional contents
deactivate xyzNutrientStorage
StorageManager --> StorageManager: loaded pre-defined nutritional contents
deactivate StorageManager

else FileNotFoundException caught
StorageManager -> xyzNutrientStorage ++: createFile()
xyzNutrientStorage --> StorageManager --: created file to store pre-defined nutritional contents
end

|||

alt successful case
StorageManager -> StorageManager: loadXYZ(xyzStorage)
activate StorageManager
StorageManager -> xyzStorage: readFile()
activate xyzStorage
xyzStorage --> StorageManager: read user's previously saved data
deactivate xyzStorage
StorageManager --> StorageManager: loaded user's previously saved data
deactivate StorageManager

else FileNotFoundException caught
StorageManager -> xyzStorage ++: createFile()
xyzStorage --> StorageManager --: created file to store user's data

else Exceptions related to saved file manipulations caught
StorageManager -> xyzStorage ++: clearFile()
xyzStorage --> StorageManager --: cleared previously saved file
end


@enduml